version: "3.8"

services:
  postgres-master:
    container_name: postgres-master
    image: postgres:latest
    restart: always
    ports:
      - "5436:5436"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=root
    networks:
      - specific-network-name

networks:
  specific-network-name:
    external: false
    name: specific-network-name