version: "3"

services:
  db1:
    image: postgres:latest
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret1
      - POSTGRES_DB=root
    volumes:
      - ./db1_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  db2:
    image: postgres:latest
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret2
      - POSTGRES_DB=root
    volumes:
      - ./db2_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres-network

  db3:
    image: postgres:latest
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret3
      - POSTGRES_DB=root
    volumes:
      - ./db3_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge